title = "class:title"
dropdown = "class:product_sort_container"
totalInCart = "class:shopping_cart_badge"
shoppingCart = "class:shopping_cart_link"
inventoryItemsList = "class:inventory_item_name"
itemPricesList = "class:inventory_item_price"
shoppingCartBadge = "class:shopping_cart_badge"
shoppingCartLink = "class:shopping_cart_link"